-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 11:39:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bizListing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bizListing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bizListing` DEFAULT CHARACTER SET utf8 ;
USE `bizListing` ;

-- -----------------------------------------------------
-- Table `bizListing`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firestname` VARCHAR(45) NULL,
  `address` VARCHAR(145) NULL,
  `tel` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address` VARCHAR(145) NULL,
  `tel` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `createTime` DATETIME NULL,
  `modifyTime` DATETIME NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`bizUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`bizUser` (
  `idbizUser` INT NOT NULL AUTO_INCREMENT,
  `bizName` VARCHAR(45) NULL,
  `address` VARCHAR(145) NULL,
  `tel` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `website` VARCHAR(145) NULL,
  `facebook` VARCHAR(145) NULL,
  `logo` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `ownerFirstname` VARCHAR(45) NULL,
  `ownerLastname` VARCHAR(45) NULL,
  `createTime` DATETIME NULL,
  `modifierTime` DATETIME NULL,
  PRIMARY KEY (`idbizUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`subCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`subCategory` (
  `idsubCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idcategory` INT NOT NULL,
  PRIMARY KEY (`idsubCategory`, `idcategory`),
  INDEX `fk_subCategory_category_idx` (`idcategory` ASC),
  CONSTRAINT `fk_subCategory_category`
    FOREIGN KEY (`idcategory`)
    REFERENCES `bizListing`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `description` VARCHAR(1045) NULL,
  `photo` VARCHAR(145) NULL,
  `iduser` INT NULL,
  `idbizUser` INT NULL,
  `idsubCategory` INT NOT NULL,
  PRIMARY KEY (`idproduct`, `idsubCategory`),
  INDEX `fk_product_user1_idx` (`iduser` ASC),
  INDEX `fk_product_bizUser1_idx` (`idbizUser` ASC),
  INDEX `fk_product_subCategory1_idx` (`idsubCategory` ASC),
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_bizUser1`
    FOREIGN KEY (`idbizUser`)
    REFERENCES `bizListing`.`bizUser` (`idbizUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_subCategory1`
    FOREIGN KEY (`idsubCategory`)
    REFERENCES `bizListing`.`subCategory` (`idsubCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`service` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `photo` VARCHAR(145) NULL,
  `hourRate` VARCHAR(45) NULL,
  `description` VARCHAR(1045) NULL,
  `iduser` INT NULL,
  `idbizUser` INT NULL,
  `idsubCategory` INT NOT NULL,
  PRIMARY KEY (`idservice`, `idsubCategory`),
  INDEX `fk_service_user1_idx` (`iduser` ASC),
  INDEX `fk_service_bizUser1_idx` (`idbizUser` ASC),
  INDEX `fk_service_subCategory1_idx` (`idsubCategory` ASC),
  CONSTRAINT `fk_service_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_bizUser1`
    FOREIGN KEY (`idbizUser`)
    REFERENCES `bizListing`.`bizUser` (`idbizUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_subCategory1`
    FOREIGN KEY (`idsubCategory`)
    REFERENCES `bizListing`.`subCategory` (`idsubCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(145) NULL,
  `content` VARCHAR(1045) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`idmessage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`inbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`inbox` (
  `idinbox` INT NOT NULL AUTO_INCREMENT,
  `idadmin` INT NULL,
  `idmessage` INT NOT NULL,
  `idbizUser` INT NULL,
  `iduser` INT NULL,
  PRIMARY KEY (`idinbox`, `idmessage`),
  INDEX `fk_inbox_admin1_idx` (`idadmin` ASC),
  INDEX `fk_inbox_message1_idx` (`idmessage` ASC),
  INDEX `fk_inbox_bizUser1_idx` (`idbizUser` ASC),
  INDEX `fk_inbox_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_inbox_admin1`
    FOREIGN KEY (`idadmin`)
    REFERENCES `bizListing`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbox_message1`
    FOREIGN KEY (`idmessage`)
    REFERENCES `bizListing`.`message` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbox_bizUser1`
    FOREIGN KEY (`idbizUser`)
    REFERENCES `bizListing`.`bizUser` (`idbizUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbox_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`outbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`outbox` (
  `idoutbox` INT NOT NULL AUTO_INCREMENT,
  `idadmin` INT NULL,
  `idmessage` INT NOT NULL,
  `idbizUser` INT NULL,
  `iduser` INT NULL,
  PRIMARY KEY (`idoutbox`, `idmessage`),
  INDEX `fk_outbox_admin1_idx` (`idadmin` ASC),
  INDEX `fk_outbox_message1_idx` (`idmessage` ASC),
  INDEX `fk_outbox_bizUser1_idx` (`idbizUser` ASC),
  INDEX `fk_outbox_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_outbox_admin1`
    FOREIGN KEY (`idadmin`)
    REFERENCES `bizListing`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_outbox_message1`
    FOREIGN KEY (`idmessage`)
    REFERENCES `bizListing`.`message` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_outbox_bizUser1`
    FOREIGN KEY (`idbizUser`)
    REFERENCES `bizListing`.`bizUser` (`idbizUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_outbox_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`annonceProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`annonceProduct` (
  `idannonce` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `idbizUser` INT NULL,
  `iduser` INT NULL,
  `idproduct` INT NOT NULL,
  PRIMARY KEY (`idannonce`, `idproduct`),
  INDEX `fk_annonceProduct_bizUser1_idx` (`idbizUser` ASC),
  INDEX `fk_annonceProduct_user1_idx` (`iduser` ASC),
  INDEX `fk_annonceProduct_product1_idx` (`idproduct` ASC),
  CONSTRAINT `fk_annonceProduct_bizUser1`
    FOREIGN KEY (`idbizUser`)
    REFERENCES `bizListing`.`bizUser` (`idbizUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonceProduct_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonceProduct_product1`
    FOREIGN KEY (`idproduct`)
    REFERENCES `bizListing`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`annonceService`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`annonceService` (
  `idannonce` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `idbizUser` INT NULL,
  `iduser` INT NULL,
  `idservice` INT NOT NULL,
  PRIMARY KEY (`idannonce`, `idservice`),
  INDEX `fk_annonceService_bizUser2_idx` (`idbizUser` ASC),
  INDEX `fk_annonceService_user1_idx` (`iduser` ASC),
  INDEX `fk_annonceService_service1_idx` (`idservice` ASC),
  CONSTRAINT `fk_annonceService_bizUser2`
    FOREIGN KEY (`idbizUser`)
    REFERENCES `bizListing`.`bizUser` (`idbizUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonceService_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonceService_service1`
    FOREIGN KEY (`idservice`)
    REFERENCES `bizListing`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `note` VARCHAR(45) NULL,
  `comment` VARCHAR(645) NULL,
  `annonceProduct_idannonce` INT NULL,
  `annonceService_idannonce` INT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_annonceProduct1_idx` (`annonceProduct_idannonce` ASC),
  INDEX `fk_comment_annonceService1_idx` (`annonceService_idannonce` ASC),
  CONSTRAINT `fk_comment_annonceProduct1`
    FOREIGN KEY (`annonceProduct_idannonce`)
    REFERENCES `bizListing`.`annonceProduct` (`idannonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_annonceService1`
    FOREIGN KEY (`annonceService_idannonce`)
    REFERENCES `bizListing`.`annonceService` (`idannonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bizListing`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bizListing`.`order` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `iduser` INT NOT NULL,
  `annonceService_idannonce` INT NULL,
  `annonceProduct_idannonce` INT NULL,
  PRIMARY KEY (`idorder`, `iduser`),
  INDEX `fk_order_user1_idx` (`iduser` ASC),
  INDEX `fk_order_annonceService1_idx` (`annonceService_idannonce` ASC),
  INDEX `fk_order_annonceProduct1_idx` (`annonceProduct_idannonce` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `bizListing`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_annonceService1`
    FOREIGN KEY (`annonceService_idannonce`)
    REFERENCES `bizListing`.`annonceService` (`idannonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_annonceProduct1`
    FOREIGN KEY (`annonceProduct_idannonce`)
    REFERENCES `bizListing`.`annonceProduct` (`idannonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
